Tools and tests (#15)
* add additional tools and tests

* activate test

* add coveralls

* add immutabledict

* Update test_package.yml

* Check folder

diff --git a/.github/workflows/test_package.yml b/.github/workflows/test_package.yml
--- a/.github/workflows/test_package.yml
+++ b/.github/workflows/test_package.yml
@@ -7,12 +7,12 @@ name: Pytest
 # Trigger this code when a new release is published
 on:
   workflow_dispatch:
-#  release:
-#    types: [ created ]
-#  pull_request:
-#  push:
-#    branches:
-#      - master
+  release:
+    types: [ created ]
+  pull_request:
+  push:
+    branches:
+      - master
 
 jobs:
   update:
@@ -21,46 +21,53 @@ jobs:
     strategy:
       fail-fast: False
       matrix:
-        os: [ "ubuntu-latest", "windows-latest" ]
-        python-version: [ "3.8", "3.9", "3.10" ]
-        test: [ 'coveralls', 'pytest', "fail-fast" ]
+        os: [ "ubuntu-latest"]
+        python-version: [ "3.8", ]
+        test: [ 'coveralls', ]
         exclude:
-          - os: windows-latest
-            test: coveralls
           - python-version: 3.9
             test: coveralls
-          - python-version: "3.10"
-            test: coveralls
-          - test: "fail-fast"
-            os: windows-latest
-          - test: "fail-fast"
-            python-version: 3.9
-          - test: "fail-fast"
-            python-version: "3.10"
+    defaults:
+      run:
+        # This is needed otherwise we can't activate the conda installation
+        shell: bash -l {0}
     steps:
-      - name: Setup python
-        uses: actions/setup-python@v4.5.0
-        with:
-          python-version: ${{ matrix.python-version }}
       - name: Checkout repo
         uses: actions/checkout@v3
+      - uses: conda-incubator/setup-miniconda@v2
+        with:
+          auto-update-conda: true
+          python-version: ${{ matrix.python-version }}
+          activate-environment: "synda"
+      - name: run install
+        run:
+          |
+            conda info
+            conda activate synda
+            git clone https://github.com/JoranAngevaare/optim_esm_base.git base_install
+            cd base_install
+            bash install_software.sh || { echo 'ERROR' ; exit 1; }
+            cd ..
+            pip install coverage pytest coveralls
+            echo ls `ls`
+            echo ls ../. `ls ../.`
+            pip install -e ../optim_esm_tools
       - name: Test package (linux)
-        if: matrix.os == 'ubuntu-latest' && matrix.test == 'pytest'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           coverage run --source=optism_esm_tools -m pytest -vsx --durations 0
-          coverage run --append --source=optism_esm_tools -m pytest --nbmake -n=auto ./notebooks
+          # coverage run --append --source=optism_esm_tools -m pytest --nbmake -n=auto ./notebooks
           coveralls --service=github
-      - name: Coveralls
-        if: matrix.test == 'coveralls'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NUMBA_DISABLE_JIT: 1
-        run: |
-          export RUN_TEST_EXTENDED=1
-          coverage run --source=optism_esm_tools setup.py test -v
-          coverage run --append --source=optism_esm_tools -m pytest --nbmake -n=auto ./notebooks
-          coveralls --service=github
+      # - name: Coveralls
+      #   if: matrix.test == 'coveralls'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     NUMBA_DISABLE_JIT: 1
+      #   run: |
+      #     export RUN_TEST_EXTENDED=1
+      #     coverage run --source=optism_esm_tools setup.py test -v
+      #     coverage run --append --source=optism_esm_tools -m pytest --nbmake -n=auto ./notebooks
+      #     coveralls --service=github
       - name: goodbye
         run: echo goodbye
